keys:
  key_name: /path/to/key/file.pem
connections:
  -
    name: <CONNECTION NAME>
    region: us-west-2
    aws_access_key_id: <AWS_ACCESS_KEY_ID>
    aws_secret_access_key: <AWS_SECRET_ACCESS_KEY>